### ISSUE TITLE
:unicode_guards version 0.4.0 is using outdated version of nimble_parsec

### ISSUE THREAD

**Issue by fireproofsocks** [elixir-unicode/unicode_guards#3]
Current version of `:nimble_parsec` is 1.1

This PR updates the version: https://github.com/elixir-unicode/unicode_guards/pull/4

**Comment by kipcole9** [comment]
Thanks for the bug report, and the PR.  I manually updated the deps so that it supports `"~> 0.5 or ~> 1.0"`.  Published as [unicode_guards version 0.5.0](https://hex.pm/packages/unicode_guards/0.5.0).  The changelog entry is:

## Bug Fixes

* Relax version requirement for `nimble_parsec` to allow `"~> 0.5 or ~> 1.0"`. Thanks to @@fireproofsocks.  Closes #3.
